### ISSUE TITLE
Is this legal?

### ISSUE THREAD

**Issue by akram-sabrouty** [Raruto/leaflet-google#3]
Isn't this against Google Maps policy?

**Comment by Raruto** [comment]
Hi sabrouty,

take a look at this other [discussion](https://github.com/mapgears/ol3-google-maps/issues/179#issuecomment-327196988) related to a similar open layers plugin:

> 
> 
> ol3-google-maps is legal. See: ~https://developers.google.com/maps/terms~ https://developers.google.com/maps/terms-20180207, under:
> 
> > 1. License Restrictions
> > 
> > 10.1 Administrative Restrictions.
> > a) No access to APIs or Content except through the Service. You will not access the Maps API(s) or the Content except through the Service. For example, you must not access map tiles or imagery through interfaces or channels (including undocumented Google interfaces) other than the Maps API(s).
> 
> ol3-google-maps **does** use the service provided by Google to request their tiles.
> 
> That being said, because of that, the library also comes with limitations. See: https://github.com/mapgears/ol3-google-maps/blob/master/LIMITATIONS.md
> 
> Other tiles providers, such as Bing, HERE, Mapbox, etc. do not have this kind of constraint, i.e. it is legal to use OpenLayers natively to request the tiles, therefore it's much easier and smoother to include those. If you absolutely need Google Maps and your project is simple enough to use their API only, then it is recommended to use their API only. If you absolutely need OpenLayers, then ol3-google-maps is a nice alternative.
> 
> Also, please read the "Our commitment" of the readme: https://github.com/mapgears/ol3-google-maps#our-commitment
> 
> HTH,
> 
> Alexandre D.

Anyway, be aware that Google updates its terms quite often and this is nothing more than a proof of a concept (check out the [GoogleMutant](https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant) library if you need a better leaflet integration).

**NB** in order to use all these libraries you still have to provide your own google map [api key](https://developers.google.com/maps/documentation/javascript/get-api-key) (otherwise you will see the "development only" warning).

_Have a nice day,
Raruto_
